name: Issues Workflow
on: 
  issues:
    types: [opened]
jobs:
  trigger-on-issues:
    runs-on: ubuntu-latest
    steps:
      - name: echo-context
        run: |
          echo "Issue number: ${{ github.event.issue.number }}"
          echo "Issue title: ${{ github.event.issue.title }}"
          echo "Created by: ${{ github.event.issue.user.login }}"
