name: Push Workflow
on: 
  push:
    paths-ignore: .github/workflows/*
jobs: 
    test-code: 
        runs-on: ubuntu-latest
        steps: 
            - name: get code
              uses: actions/checkout@v3
            - name: install dependencies
              run: npm ci
            - name: run lint
              run: npm run lint
            - name: run test
              run: npm test
    build-code:
        runs-on: ubuntu-latest
        needs: test-code
        steps:
            - name: get code
              uses: actions/checkout@v3
            - name: install dependencies
              run: npm ci
            - name: build code 
              run: npm run build
        
